In [1]:
import pandas as pd

In [2]:
import warnings

In [3]:
warnings.filterwarnings("ignore")

In [4]:
data=pd.read_csv(r'C:\Users\deyar\OneDrive\Desktop\GrocaryBasketAnalysis\notebooks\data\Assignment-1_Data.csv')

In [5]:
data.head()

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [6]:
data.isnull().sum()

BillNo             0
Itemname        1455
Quantity           0
Date               0
Price              0
CustomerID    134041
Country            0
dtype: int64

In [7]:
data.dropna(subset=['Itemname'],inplace=True)

In [8]:
data.isnull().sum()

BillNo             0
Itemname           0
Quantity           0
Date               0
Price              0
CustomerID    132586
Country            0
dtype: int64

In [9]:
data['BillNo'].value_counts()

BillNo
573585    1114
581219     749
581492     731
580729     721
558475     705
          ...
567149       1
567150       1
567152       1
555751       1
549850       1
Name: count, Length: 20210, dtype: int64

In [10]:
data['CustomerID'].value_counts()

CustomerID
17841.0    7847
14096.0    5111
12748.0    4596
14606.0    2700
15311.0    2379
           ...
12346.0       1
18268.0       1
17846.0       1
16742.0       1
15940.0       1
Name: count, Length: 4297, dtype: int64

In [39]:
data.dropna(inplace=True)

In [42]:
data.duplicated().sum()

5210

In [43]:
data.drop_duplicates(inplace=True)

In [44]:
data.shape

(382813, 7)

In [45]:
d1=data.groupby('CustomerID')['Itemname'].apply(list).to_list()

In [46]:
d1[8]

['BAKING SET 9 PIECE RETROSPOT',
 'WHITE HEART CONFETTI IN TUBE',
 'LAVENDER SCENTED FABRIC HEART',
 'PINK  HEART CONFETTI IN TUBE',
 'SWEETHEART CERAMIC TRINKET BOX',
 'LARGE CAKE STAND HANGING HEARTS',
 'CERAMIC BOWL WITH LOVE HEART DESIGN',
 'LOVE HEART TRINKET POT',
 'RED LOVE HEART SHAPE CUP',
 'FOOD CONTAINER SET 3 LOVE HEART',
 'LARGE HEART MEASURING SPOONS',
 'SET OF 9 HEART SHAPED BALLOONS',
 'BAKING MOULD CHOCOLATE CUPCAKES',
 'SET OF 3 HEART COOKIE CUTTERS',
 'PACK 6 HEART/ICE-CREAM PATCHES',
 '72 SWEETHEART FAIRY CAKE CASES',
 'S/4 VALENTINE DECOUPAGE HEART BOX',
 'MINI CAKE STAND  HANGING STRAWBERY',
 'CERAMIC STRAWBERRY DESIGN MUG',
 'STRAWBERRY FAIRY CAKE TEAPOT',
 'CERAMIC STRAWBERRY CAKE MONEY BANK',
 'CERAMIC CAKE DESIGN SPOTTED MUG',
 'CERAMIC CAKE BOWL + HANGING CAKES',
 'TEA TIME TEAPOT IN GIFT BOX',
 'TEA TIME TEA SET IN GIFT BOX',
 '60 TEATIME FAIRY CAKE CASES',
 'SET OF 36 TEATIME PAPER DOILIES',
 'FAIRY CAKES NOTEBOOK A6 SIZE',
 'REGENCY CAKESTAND 3 TIER',
 'SET OF 20 KIDS COOKIE CUTTERS',
 'SET OF 3 BUTTERFLY COOKIE CUTTERS',
 '60 CAKE CASES DOLLY GIRL DESIGN',
 'PACK OF 72 SKULL CAKE CASES',
 'RED RETROSPOT TRADITIONAL TEAPOT',
 'RED RETROSPOT CAKE STAND',
 'POSTAGE',
 '60 TEATIME FAIRY CAKE CASES',
 'PACK OF 72 RETROSPOT CAKE CASES',
 'CUPCAKE LACE PAPER SET 6',
 'SET/10 BLUE POLKADOT PARTY CANDLES',
 'SET/3 RABBITS FLOWER SKIPPPING ROPE',
 'ASSORTED EASTER GIFT TAGS',
 'SET/10 PINK POLKADOT PARTY CANDLES',
 'SET 6 FOOTBALL CELEBRATION CANDLES',
 'SET 3 SONG BIRD PAPER EGGS ASSORTED',
 'SET 3 PAPER VINTAGE CHICK PAPER EGG',
 'SET/6 RED SPOTTY PAPER CUPS',
 'SET/20 RED RETROSPOT PAPER NAPKINS',
 'PINK BLUE FELT CRAFT TRINKET BOX',
 'SET OF 3 HEART COOKIE CUTTERS',
 'SET/6 RED SPOTTY PAPER PLATES',
 'CERAMIC CAKE DESIGN SPOTTED PLATE',
 'REGENCY CAKESTAND 3 TIER',
 'PACK OF 12 STICKY BUNNIES',
 'PINK REGENCY TEACUP AND SAUCER',
 'ROSES REGENCY TEACUP AND SAUCER',
 'RED RETROSPOT CAKE STAND',
 'REGENCY CAKESTAND 3 TIER',
 'RED RETROSPOT CAKE STAND']

In [47]:
from mlxtend.preprocessing import TransactionEncoder

In [48]:
pre=TransactionEncoder()

In [49]:
res1=pre.fit_transform(d1)

In [50]:
d2=pd.DataFrame(res1,columns=pre.columns_)

In [51]:
d2.head()

,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 DAISY PEGS IN WOOD BOX,12 EGG HOUSE PAINTED WOOD,12 HANGING EGGS HAND PAINTED,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [52]:
d2.replace(False,0,inplace=True)
d2.replace(True,1,inplace=True)

In [53]:
d2.head()

,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 DAISY PEGS IN WOOD BOX,12 EGG HOUSE PAINTED WOOD,12 HANGING EGGS HAND PAINTED,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [54]:
from mlxtend.frequent_patterns import apriori,association_rules

In [58]:
support=apriori(d2,min_support=.05,use_colnames=True)

c:\Users\deyar\OneDrive\Desktop\GrocaryBasketAnalysis\apriory\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [59]:
support.sort_values(by='support',ascending=False).head()

      support                              itemsets
183  0.202234            (REGENCY CAKESTAND 3 TIER)
244  0.196416  (WHITE HANGING HEART T-LIGHT HOLDER)
149  0.162439                       (PARTY BUNTING)
15   0.156621       (ASSORTED COLOUR BIRD ORNAMENT)
204  0.147079    (SET OF 3 CAKE TINS PANTRY DESIGN)

In [60]:
confidence=association_rules(support,metric='confidence',min_threshold=.5)

In [61]:
confidence.sort_values(by='confidence',ascending=False).head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
128,"(PINK REGENCY TEACUP AND SAUCER, ROSES REGENCY...",(GREEN REGENCY TEACUP AND SAUCER),0.053293,0.088667,0.051199,0.960699,10.834967,0.046473,23.188374,0.958804
101,"(PINK REGENCY TEACUP AND SAUCER, ROSES REGENCY...",(GREEN REGENCY TEACUP AND SAUCER),0.062369,0.088667,0.059809,0.958955,10.815303,0.054279,22.203398,0.967906
96,"(PINK REGENCY TEACUP AND SAUCER, REGENCY CAKES...",(GREEN REGENCY TEACUP AND SAUCER),0.059344,0.088667,0.056086,0.945098,10.659019,0.050824,16.599289,0.963352
10,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.073307,0.088667,0.067954,0.926984,10.454726,0.061455,12.481306,0.975889
127,"(PINK REGENCY TEACUP AND SAUCER, GREEN REGENCY...",(ROSES REGENCY TEACUP AND SAUCER),0.056086,0.097044,0.051199,0.912863,9.406649,0.045756,10.362490,0.946794

lift shows correlation between items ,it can be +ve or -ve ,basically it shows strength of association

In [62]:
final=confidence[confidence['lift']>1] #posetive correlation

In [65]:
final.sort_values(by='lift',ascending=False).head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
131,"(PINK REGENCY TEACUP AND SAUCER, ROSES REGENCY...","(GREEN REGENCY TEACUP AND SAUCER, REGENCY CAKE...",0.062369,0.067722,0.051199,0.820896,12.121608,0.046975,5.205221,0.978533
134,"(GREEN REGENCY TEACUP AND SAUCER, REGENCY CAKE...","(PINK REGENCY TEACUP AND SAUCER, ROSES REGENCY...",0.067722,0.062369,0.051199,0.756014,12.121608,0.046975,3.842966,0.984151
136,(PINK REGENCY TEACUP AND SAUCER),"(ROSES REGENCY TEACUP AND SAUCER, GREEN REGENC...",0.073307,0.058878,0.051199,0.698413,11.861974,0.046882,3.120561,0.988134
129,"(ROSES REGENCY TEACUP AND SAUCER, GREEN REGENC...",(PINK REGENCY TEACUP AND SAUCER),0.058878,0.073307,0.051199,0.869565,11.861974,0.046882,7.104647,0.972985
132,"(PINK REGENCY TEACUP AND SAUCER, REGENCY CAKES...","(ROSES REGENCY TEACUP AND SAUCER, GREEN REGENC...",0.059344,0.073307,0.051199,0.862745,11.768939,0.046848,6.751621,0.972758

In [67]:
final2=confidence[confidence['lift']<1] #negetive correlation

In [68]:
final2.sort_values(by='lift',ascending=False).head()

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction, zhangs_metric]
Index: []

In [69]:
final3=confidence[confidence['lift']==1] #no correalation

In [70]:
final3.sort_values(by='lift',ascending=False).head()

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction, zhangs_metric]
Index: []